//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class AuthSignIn:public drogon::DrTemplate<AuthSignIn>
{
public:
	AuthSignIn(){};
	virtual ~AuthSignIn(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
