//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "AuthSignIn.h"
#include <drogon/utils/OStringStream.h>
#include <drogon/utils/Utilities.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string AuthSignIn::genText(const DrTemplateData& AuthSignIn_view_data)
{
	drogon::OStringStream AuthSignIn_tmp_stream;
	std::string layoutName{""};
	AuthSignIn_tmp_stream << "<!DOCTYPE html>\n";
	AuthSignIn_tmp_stream << "<html lang=\"en\" data-theme=\"silk\">\n";
	AuthSignIn_tmp_stream << "<head>\n";
	AuthSignIn_tmp_stream << "  <meta charset=\"UTF-8\">\n";
	AuthSignIn_tmp_stream << "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	AuthSignIn_tmp_stream << "  <title>Sign In - Ak ACL</title>\n";
	AuthSignIn_tmp_stream << "  <link href=\"https://cdn.jsdelivr.net/npm/daisyui@4.12.14/dist/full.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n";
	AuthSignIn_tmp_stream << "  <script src=\"https://cdn.tailwindcss.com\"></script>\n";
	AuthSignIn_tmp_stream << "  <style>\n";
	AuthSignIn_tmp_stream << "    [data-theme=\"silk\"] {\n";
	AuthSignIn_tmp_stream << "      color-scheme: light;\n";
	AuthSignIn_tmp_stream << "      --rounded-box: 1rem; --rounded-btn: 0.5rem; --rounded-badge: 2rem;\n";
	AuthSignIn_tmp_stream << "      --animation-btn: 0.25s; --animation-input: 0.2s; --btn-focus-scale: 0.95;\n";
	AuthSignIn_tmp_stream << "      --border-btn: 2px; --tab-border: 2px; --tab-radius: 0.5rem;\n";
	AuthSignIn_tmp_stream << "      --b1: 97% 0.0035 67.78; --b2: 95% 0.0081 61.42; --b3: 90% 0.0081 61.42; --bc: 40% 0.0081 61.42;\n";
	AuthSignIn_tmp_stream << "      --p: 23.27% 0.0249 284.3; --pc: 94.22% 0.2505 117.44;\n";
	AuthSignIn_tmp_stream << "      --s: 23.27% 0.0249 284.3; --sc: 73.92% 0.2135 50.94;\n";
	AuthSignIn_tmp_stream << "      --a: 23.27% 0.0249 284.3; --ac: 88.92% 0.2061 189.9;\n";
	AuthSignIn_tmp_stream << "      --n: 20% 0 0; --nc: 80% 0.0081 61.42;\n";
	AuthSignIn_tmp_stream << "      --in: 80.39% 0.1148 241.68; --inc: 30.39% 0.1148 241.68;\n";
	AuthSignIn_tmp_stream << "      --su: 83.92% 0.0901 136.87; --suc: 23.92% 0.0901 136.87;\n";
	AuthSignIn_tmp_stream << "      --wa: 83.92% 0.1085 80; --wac: 43.92% 0.1085 80;\n";
	AuthSignIn_tmp_stream << "      --er: 75.1% 0.1814 22.37; --erc: 35.1% 0.1814 22.37;\n";
	AuthSignIn_tmp_stream << "    }\n";
	AuthSignIn_tmp_stream << "  </style>\n";
	AuthSignIn_tmp_stream << "</head>\n";
	AuthSignIn_tmp_stream << "<body class=\"min-h-screen flex items-center justify-center bg-base-200\">\n";
	AuthSignIn_tmp_stream << "  <div class=\"card w-full max-w-md bg-base-100 shadow-xl\">\n";
	AuthSignIn_tmp_stream << "    <div class=\"card-body\">\n";
	AuthSignIn_tmp_stream << "      <h2 class=\"card-title text-3xl font-bold text-center justify-center mb-2\">Ak ACL 🩴</h2>\n";
	AuthSignIn_tmp_stream << "      <p class=\"text-center text-base-content/70 mb-6\">Sign in to your account to continue</p>\n";
AuthSignIn_tmp_stream<<"\n";
	AuthSignIn_tmp_stream << "      ";
 auto message = AuthSignIn_view_data.get<std::string>("message"); 
	AuthSignIn_tmp_stream << "      ";
 if (!message.empty()) { 
	AuthSignIn_tmp_stream << "      <div class=\"alert alert-error\">\n";
	AuthSignIn_tmp_stream << "        <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"stroke-current shrink-0 h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z\" /></svg>\n";
	AuthSignIn_tmp_stream << "        <span>";
 AuthSignIn_tmp_stream<<message; 
	AuthSignIn_tmp_stream << "</span>\n";
	AuthSignIn_tmp_stream << "      </div>\n";
	AuthSignIn_tmp_stream << "      ";
 } 
AuthSignIn_tmp_stream<<"\n";
	AuthSignIn_tmp_stream << "      <form method=\"POST\" action=\"/ak-acl/auth/signin?to=/ak-acl/management/employee/control\" class=\"space-y-4\">\n";
	AuthSignIn_tmp_stream << "        <div class=\"form-control\">\n";
	AuthSignIn_tmp_stream << "          <input\n";
	AuthSignIn_tmp_stream << "            type=\"text\"\n";
	AuthSignIn_tmp_stream << "            id=\"username\"\n";
	AuthSignIn_tmp_stream << "            name=\"username\"\n";
	AuthSignIn_tmp_stream << "            placeholder=\"Enter your username\"\n";
	AuthSignIn_tmp_stream << "            class=\"input input-bordered w-full\"\n";
	AuthSignIn_tmp_stream << "            required\n";
	AuthSignIn_tmp_stream << "            autocomplete=\"username\"\n";
	AuthSignIn_tmp_stream << "            autofocus\n";
	AuthSignIn_tmp_stream << "          />\n";
	AuthSignIn_tmp_stream << "        </div>\n";
AuthSignIn_tmp_stream<<"\n";
	AuthSignIn_tmp_stream << "        <div class=\"form-control\">\n";
	AuthSignIn_tmp_stream << "          <input\n";
	AuthSignIn_tmp_stream << "            type=\"password\"\n";
	AuthSignIn_tmp_stream << "            id=\"password\"\n";
	AuthSignIn_tmp_stream << "            name=\"password\"\n";
	AuthSignIn_tmp_stream << "            placeholder=\"Enter your password\"\n";
	AuthSignIn_tmp_stream << "            class=\"input input-bordered w-full\"\n";
	AuthSignIn_tmp_stream << "            required\n";
	AuthSignIn_tmp_stream << "            autocomplete=\"current-password\"\n";
	AuthSignIn_tmp_stream << "          />\n";
	AuthSignIn_tmp_stream << "        </div>\n";
AuthSignIn_tmp_stream<<"\n";
	AuthSignIn_tmp_stream << "        <div class=\"form-control\">\n";
	AuthSignIn_tmp_stream << "          <button type=\"submit\" class=\"btn btn-primary w-full\">Sign In</button>\n";
	AuthSignIn_tmp_stream << "        </div>\n";
	AuthSignIn_tmp_stream << "      </form>\n";
AuthSignIn_tmp_stream<<"\n";
	AuthSignIn_tmp_stream << "      <div class=\"divider text-xs text-base-content/50\">OR</div>\n";
AuthSignIn_tmp_stream<<"\n";
	AuthSignIn_tmp_stream << "      <div class=\"text-center text-sm\">\n";
	AuthSignIn_tmp_stream << "        <span class=\"text-base-content/70\">Don't have an account?</span>\n";
	AuthSignIn_tmp_stream << "        <a href=\"/auth/register\" class=\"link link-primary font-medium ml-1\">Sign up</a>\n";
	AuthSignIn_tmp_stream << "      </div>\n";
	AuthSignIn_tmp_stream << "    </div>\n";
	AuthSignIn_tmp_stream << "  </div>\n";
	AuthSignIn_tmp_stream << "</body>\n";
	AuthSignIn_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(AuthSignIn_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = AuthSignIn_view_data;
auto str = std::move(AuthSignIn_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
