//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "ManagementEmployeeControlList.h"
#include <drogon/utils/OStringStream.h>
#include <drogon/utils/Utilities.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string ManagementEmployeeControlList::genText(const DrTemplateData& ManagementEmployeeControlList_view_data)
{
	drogon::OStringStream ManagementEmployeeControlList_tmp_stream;
	std::string layoutName{""};
	ManagementEmployeeControlList_tmp_stream << "<div id=\"employee-list\" class=\"card bg-base-100 shadow-xl\">\n";
	ManagementEmployeeControlList_tmp_stream << "<div class=\"card-body\">\n";
	ManagementEmployeeControlList_tmp_stream << "  ";
 auto search = ManagementEmployeeControlList_view_data.get<std::string>("search"); 
ManagementEmployeeControlList_tmp_stream<<"\n";
	ManagementEmployeeControlList_tmp_stream << "  <div class=\"mb-4\">\n";
	ManagementEmployeeControlList_tmp_stream << "    <div class=\"form-control\">\n";
	ManagementEmployeeControlList_tmp_stream << "      <div class=\"join w-full\">\n";
	ManagementEmployeeControlList_tmp_stream << "        <input\n";
	ManagementEmployeeControlList_tmp_stream << "          type=\"text\"\n";
	ManagementEmployeeControlList_tmp_stream << "          name=\"search\"\n";
	ManagementEmployeeControlList_tmp_stream << "          placeholder=\"Buscar por nombre, placa o documento...\"\n";
	ManagementEmployeeControlList_tmp_stream << "          class=\"input input-bordered join-item w-full\"\n";
	ManagementEmployeeControlList_tmp_stream << "          value=\"";
 ManagementEmployeeControlList_tmp_stream<<search; 
	ManagementEmployeeControlList_tmp_stream << "\"\n";
	ManagementEmployeeControlList_tmp_stream << "          hx-get=\"/ak-acl/management/employee/control/list\"\n";
	ManagementEmployeeControlList_tmp_stream << "          hx-trigger=\"keyup changed delay:500ms, search\"\n";
	ManagementEmployeeControlList_tmp_stream << "          hx-target=\"#employee-list\"\n";
	ManagementEmployeeControlList_tmp_stream << "          hx-swap=\"outerHTML\"\n";
	ManagementEmployeeControlList_tmp_stream << "          hx-include=\"this\" />\n";
	ManagementEmployeeControlList_tmp_stream << "        ";
 if (!search.empty()) { 
	ManagementEmployeeControlList_tmp_stream << "        <button\n";
	ManagementEmployeeControlList_tmp_stream << "          class=\"btn btn-square join-item\"\n";
	ManagementEmployeeControlList_tmp_stream << "          hx-get=\"/ak-acl/management/employee/control/list\"\n";
	ManagementEmployeeControlList_tmp_stream << "          hx-target=\"#employee-list\"\n";
	ManagementEmployeeControlList_tmp_stream << "          hx-swap=\"outerHTML\">\n";
	ManagementEmployeeControlList_tmp_stream << "          <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\n";
	ManagementEmployeeControlList_tmp_stream << "            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M6 18L18 6M6 6l12 12\" />\n";
	ManagementEmployeeControlList_tmp_stream << "          </svg>\n";
	ManagementEmployeeControlList_tmp_stream << "        </button>\n";
	ManagementEmployeeControlList_tmp_stream << "        ";
 } 
	ManagementEmployeeControlList_tmp_stream << "      </div>\n";
	ManagementEmployeeControlList_tmp_stream << "    </div>\n";
	ManagementEmployeeControlList_tmp_stream << "  </div>\n";
ManagementEmployeeControlList_tmp_stream<<"\n";
	ManagementEmployeeControlList_tmp_stream << "  <div class=\"overflow-x-auto\">\n";
	ManagementEmployeeControlList_tmp_stream << "    <table class=\"table table-zebra\">\n";
	ManagementEmployeeControlList_tmp_stream << "      <thead>\n";
	ManagementEmployeeControlList_tmp_stream << "        <tr>\n";
	ManagementEmployeeControlList_tmp_stream << "          <th>ID</th>\n";
	ManagementEmployeeControlList_tmp_stream << "          <th>Nombre</th>\n";
	ManagementEmployeeControlList_tmp_stream << "          <th>Placa</th>\n";
	ManagementEmployeeControlList_tmp_stream << "          <th>Tipo de Documento</th>\n";
	ManagementEmployeeControlList_tmp_stream << "          <th>Número de Documento</th>\n";
	ManagementEmployeeControlList_tmp_stream << "        </tr>\n";
	ManagementEmployeeControlList_tmp_stream << "      </thead>\n";
	ManagementEmployeeControlList_tmp_stream << "      <tbody id=\"employeeTableBody\">\n";
	ManagementEmployeeControlList_tmp_stream << "        ";
 auto employees = ManagementEmployeeControlList_view_data.get<std::vector<std::map<std::string, std::string>>>("employees"); 
	ManagementEmployeeControlList_tmp_stream << "        ";
 for (const auto& employee : employees) { 
	ManagementEmployeeControlList_tmp_stream << "        <tr>\n";
	ManagementEmployeeControlList_tmp_stream << "          <td>";
 ManagementEmployeeControlList_tmp_stream<<employee.at("id"); 
	ManagementEmployeeControlList_tmp_stream << "</td>\n";
	ManagementEmployeeControlList_tmp_stream << "          <td>";
 ManagementEmployeeControlList_tmp_stream<<employee.at("name"); 
	ManagementEmployeeControlList_tmp_stream << "</td>\n";
	ManagementEmployeeControlList_tmp_stream << "          <td><span class=\"badge badge-primary\">";
 ManagementEmployeeControlList_tmp_stream<<employee.at("plate"); 
	ManagementEmployeeControlList_tmp_stream << "</span></td>\n";
	ManagementEmployeeControlList_tmp_stream << "          <td><span class=\"badge badge-outline\">";
 ManagementEmployeeControlList_tmp_stream<<employee.at("document_type"); 
	ManagementEmployeeControlList_tmp_stream << "</span></td>\n";
	ManagementEmployeeControlList_tmp_stream << "          <td>";
 ManagementEmployeeControlList_tmp_stream<<employee.at("document_number"); 
	ManagementEmployeeControlList_tmp_stream << "</td>\n";
	ManagementEmployeeControlList_tmp_stream << "        </tr>\n";
	ManagementEmployeeControlList_tmp_stream << "        ";
 } 
	ManagementEmployeeControlList_tmp_stream << "      </tbody>\n";
	ManagementEmployeeControlList_tmp_stream << "    </table>\n";
	ManagementEmployeeControlList_tmp_stream << "  </div>\n";
ManagementEmployeeControlList_tmp_stream<<"\n";
	ManagementEmployeeControlList_tmp_stream << "  ";
 auto currentPage = ManagementEmployeeControlList_view_data.get<int>("currentPage"); 
	ManagementEmployeeControlList_tmp_stream << "  ";
 auto totalPages = ManagementEmployeeControlList_view_data.get<int>("totalPages"); 
	ManagementEmployeeControlList_tmp_stream << "  ";
 auto totalEmployees = ManagementEmployeeControlList_view_data.get<int>("totalEmployees"); 
	ManagementEmployeeControlList_tmp_stream << "  ";
 auto pageSize = ManagementEmployeeControlList_view_data.get<int>("pageSize"); 
ManagementEmployeeControlList_tmp_stream<<"\n";
	ManagementEmployeeControlList_tmp_stream << "  <div class=\"flex flex-col items-center gap-4 mt-6\">\n";
	ManagementEmployeeControlList_tmp_stream << "    <div class=\"text-sm text-base-content/70\">\n";
	ManagementEmployeeControlList_tmp_stream << "      Mostrando ";
 ManagementEmployeeControlList_tmp_stream<<std::to_string((currentPage - 1) * pageSize + 1); 
	ManagementEmployeeControlList_tmp_stream << "      - ";
 ManagementEmployeeControlList_tmp_stream<<std::to_string(std::min(currentPage * pageSize, totalEmployees)); 
	ManagementEmployeeControlList_tmp_stream << "      de ";
 ManagementEmployeeControlList_tmp_stream<<std::to_string(totalEmployees); 
	ManagementEmployeeControlList_tmp_stream << " empleados\n";
	ManagementEmployeeControlList_tmp_stream << "    </div>\n";
ManagementEmployeeControlList_tmp_stream<<"\n";
	ManagementEmployeeControlList_tmp_stream << "    ";
 if (totalPages > 1) { 
	ManagementEmployeeControlList_tmp_stream << "    <div class=\"join\">\n";
	ManagementEmployeeControlList_tmp_stream << "      ";
 if (currentPage > 1) { 
	ManagementEmployeeControlList_tmp_stream << "      <button\n";
	ManagementEmployeeControlList_tmp_stream << "        class=\"join-item btn btn-sm\"\n";
	ManagementEmployeeControlList_tmp_stream << "        hx-get=\"/ak-acl/management/employee/control/list?page=";
 ManagementEmployeeControlList_tmp_stream<<std::to_string(currentPage - 1); 
 if (!search.empty()) { ManagementEmployeeControlList_tmp_stream<<"&search=" + search; } 
	ManagementEmployeeControlList_tmp_stream << "\"\n";
	ManagementEmployeeControlList_tmp_stream << "        hx-target=\"#employee-list\"\n";
	ManagementEmployeeControlList_tmp_stream << "        hx-swap=\"outerHTML\">«</button>\n";
	ManagementEmployeeControlList_tmp_stream << "      ";
 } else { 
	ManagementEmployeeControlList_tmp_stream << "      <button class=\"join-item btn btn-sm btn-disabled\">«</button>\n";
	ManagementEmployeeControlList_tmp_stream << "      ";
 } 
ManagementEmployeeControlList_tmp_stream<<"\n";
	ManagementEmployeeControlList_tmp_stream << "      ";
      int maxButtons = 5;
      int startPage = std::max(1, currentPage - maxButtons / 2);
      int endPage = std::min(totalPages, startPage + maxButtons - 1);
      if (endPage - startPage < maxButtons - 1) {
        startPage = std::max(1, endPage - maxButtons + 1);
      }
      for (int i = startPage; i <= endPage; i++) {
      
	ManagementEmployeeControlList_tmp_stream << "        ";
 if (i == currentPage) { 
	ManagementEmployeeControlList_tmp_stream << "        <button class=\"join-item btn btn-sm btn-active\">";
 ManagementEmployeeControlList_tmp_stream<<std::to_string(i); 
	ManagementEmployeeControlList_tmp_stream << "</button>\n";
	ManagementEmployeeControlList_tmp_stream << "        ";
 } else { 
	ManagementEmployeeControlList_tmp_stream << "        <button\n";
	ManagementEmployeeControlList_tmp_stream << "          class=\"join-item btn btn-sm\"\n";
	ManagementEmployeeControlList_tmp_stream << "          hx-get=\"/ak-acl/management/employee/control/list?page=";
 ManagementEmployeeControlList_tmp_stream<<std::to_string(i); 
 if (!search.empty()) { ManagementEmployeeControlList_tmp_stream<<"&search=" + search; } 
	ManagementEmployeeControlList_tmp_stream << "\"\n";
	ManagementEmployeeControlList_tmp_stream << "          hx-target=\"#employee-list\"\n";
	ManagementEmployeeControlList_tmp_stream << "          hx-swap=\"outerHTML\">";
 ManagementEmployeeControlList_tmp_stream<<std::to_string(i); 
	ManagementEmployeeControlList_tmp_stream << "</button>\n";
	ManagementEmployeeControlList_tmp_stream << "        ";
 } 
	ManagementEmployeeControlList_tmp_stream << "      ";
 } 
ManagementEmployeeControlList_tmp_stream<<"\n";
	ManagementEmployeeControlList_tmp_stream << "      ";
 if (currentPage < totalPages) { 
	ManagementEmployeeControlList_tmp_stream << "      <button\n";
	ManagementEmployeeControlList_tmp_stream << "        class=\"join-item btn btn-sm\"\n";
	ManagementEmployeeControlList_tmp_stream << "        hx-get=\"/ak-acl/management/employee/control/list?page=";
 ManagementEmployeeControlList_tmp_stream<<std::to_string(currentPage + 1); 
 if (!search.empty()) { ManagementEmployeeControlList_tmp_stream<<"&search=" + search; } 
	ManagementEmployeeControlList_tmp_stream << "\"\n";
	ManagementEmployeeControlList_tmp_stream << "        hx-target=\"#employee-list\"\n";
	ManagementEmployeeControlList_tmp_stream << "        hx-swap=\"outerHTML\">»</button>\n";
	ManagementEmployeeControlList_tmp_stream << "      ";
 } else { 
	ManagementEmployeeControlList_tmp_stream << "      <button class=\"join-item btn btn-sm btn-disabled\">»</button>\n";
	ManagementEmployeeControlList_tmp_stream << "      ";
 } 
	ManagementEmployeeControlList_tmp_stream << "    </div>\n";
	ManagementEmployeeControlList_tmp_stream << "    ";
 } 
	ManagementEmployeeControlList_tmp_stream << "  </div>\n";
	ManagementEmployeeControlList_tmp_stream << "</div>\n";
	ManagementEmployeeControlList_tmp_stream << "</div>\n";
if(layoutName.empty())
{
std::string ret{std::move(ManagementEmployeeControlList_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = ManagementEmployeeControlList_view_data;
auto str = std::move(ManagementEmployeeControlList_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
