//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "ManagementEmployeeControl.h"
#include <drogon/utils/OStringStream.h>
#include <drogon/utils/Utilities.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string ManagementEmployeeControl::genText(const DrTemplateData& ManagementEmployeeControl_view_data)
{
	drogon::OStringStream ManagementEmployeeControl_tmp_stream;
	std::string layoutName{""};
	ManagementEmployeeControl_tmp_stream << "<!DOCTYPE html>\n";
	ManagementEmployeeControl_tmp_stream << "<html lang=\"en\" data-theme=\"silk\">\n";
	ManagementEmployeeControl_tmp_stream << "<head>\n";
	ManagementEmployeeControl_tmp_stream << "  <meta charset=\"UTF-8\">\n";
	ManagementEmployeeControl_tmp_stream << "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	ManagementEmployeeControl_tmp_stream << "  <title>Control de Empleados - Ak ACL</title>\n";
	ManagementEmployeeControl_tmp_stream << "  <link href=\"https://cdn.jsdelivr.net/npm/daisyui@4.12.14/dist/full.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n";
	ManagementEmployeeControl_tmp_stream << "  <script src=\"https://cdn.tailwindcss.com\"></script>\n";
	ManagementEmployeeControl_tmp_stream << "  <script src=\"https://cdn.jsdelivr.net/npm/htmx.org@2.0.10/dist/htmx.min.js\" integrity=\"sha384-H5SrcfygHmAuTDZphMHqBJLc3FhssKjG7w/CeCpFReSfwBWDTKpkzPP8c+cLsK+V\" crossorigin=\"anonymous\"></script>\n";
	ManagementEmployeeControl_tmp_stream << "  <style>\n";
	ManagementEmployeeControl_tmp_stream << "    [data-theme=\"silk\"] {\n";
	ManagementEmployeeControl_tmp_stream << "      color-scheme: light;\n";
	ManagementEmployeeControl_tmp_stream << "      --rounded-box: 1rem; --rounded-btn: 0.5rem; --rounded-badge: 2rem;\n";
	ManagementEmployeeControl_tmp_stream << "      --animation-btn: 0.25s; --animation-input: 0.2s; --btn-focus-scale: 0.95;\n";
	ManagementEmployeeControl_tmp_stream << "      --border-btn: 2px; --tab-border: 2px; --tab-radius: 0.5rem;\n";
	ManagementEmployeeControl_tmp_stream << "      --b1: 97% 0.0035 67.78; --b2: 95% 0.0081 61.42; --b3: 90% 0.0081 61.42; --bc: 40% 0.0081 61.42;\n";
	ManagementEmployeeControl_tmp_stream << "      --p: 23.27% 0.0249 284.3; --pc: 94.22% 0.2505 117.44;\n";
	ManagementEmployeeControl_tmp_stream << "      --s: 23.27% 0.0249 284.3; --sc: 73.92% 0.2135 50.94;\n";
	ManagementEmployeeControl_tmp_stream << "      --a: 23.27% 0.0249 284.3; --ac: 88.92% 0.2061 189.9;\n";
	ManagementEmployeeControl_tmp_stream << "      --n: 20% 0 0; --nc: 80% 0.0081 61.42;\n";
	ManagementEmployeeControl_tmp_stream << "      --in: 80.39% 0.1148 241.68; --inc: 30.39% 0.1148 241.68;\n";
	ManagementEmployeeControl_tmp_stream << "      --su: 83.92% 0.0901 136.87; --suc: 23.92% 0.0901 136.87;\n";
	ManagementEmployeeControl_tmp_stream << "      --wa: 83.92% 0.1085 80; --wac: 43.92% 0.1085 80;\n";
	ManagementEmployeeControl_tmp_stream << "      --er: 75.1% 0.1814 22.37; --erc: 35.1% 0.1814 22.37;\n";
	ManagementEmployeeControl_tmp_stream << "    }\n";
	ManagementEmployeeControl_tmp_stream << "  </style>\n";
	ManagementEmployeeControl_tmp_stream << "</head>\n";
	ManagementEmployeeControl_tmp_stream << "<body class=\"min-h-screen bg-base-200\">\n";
	ManagementEmployeeControl_tmp_stream << "  <div class=\"container mx-auto px-4 py-8\">\n";
	ManagementEmployeeControl_tmp_stream << "    <div class=\"mb-6 flex justify-between items-center\">\n";
	ManagementEmployeeControl_tmp_stream << "      <div>\n";
	ManagementEmployeeControl_tmp_stream << "        <h1 class=\"text-4xl font-bold\">Control de Empleados</h1>\n";
	ManagementEmployeeControl_tmp_stream << "        <p class=\"text-base-content/70 mt-2\">Gestiona tu inventario de empleados</p>\n";
	ManagementEmployeeControl_tmp_stream << "      </div>\n";
	ManagementEmployeeControl_tmp_stream << "      <button\n";
	ManagementEmployeeControl_tmp_stream << "        class=\"btn btn-primary\"\n";
	ManagementEmployeeControl_tmp_stream << "        hx-get=\"/ak-acl/management/employee/control/create\"\n";
	ManagementEmployeeControl_tmp_stream << "        hx-target=\"#employee-form\"\n";
	ManagementEmployeeControl_tmp_stream << "        hx-swap=\"innerHTML\">\n";
	ManagementEmployeeControl_tmp_stream << "        Agregar Empleado\n";
	ManagementEmployeeControl_tmp_stream << "      </button>\n";
	ManagementEmployeeControl_tmp_stream << "    </div>\n";
ManagementEmployeeControl_tmp_stream<<"\n";
	ManagementEmployeeControl_tmp_stream << "    <div id=\"employee-form\" class=\"mb-6\"></div>\n";
ManagementEmployeeControl_tmp_stream<<"\n";
	ManagementEmployeeControl_tmp_stream << "    <div\n";
	ManagementEmployeeControl_tmp_stream << "      id=\"employee-list\"\n";
	ManagementEmployeeControl_tmp_stream << "      hx-get=\"/ak-acl/management/employee/control/list\"\n";
	ManagementEmployeeControl_tmp_stream << "      hx-trigger=\"load\"\n";
	ManagementEmployeeControl_tmp_stream << "      hx-swap=\"outerHTML\"></div>\n";
	ManagementEmployeeControl_tmp_stream << "  </div>\n";
	ManagementEmployeeControl_tmp_stream << "</body>\n";
	ManagementEmployeeControl_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(ManagementEmployeeControl_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = ManagementEmployeeControl_view_data;
auto str = std::move(ManagementEmployeeControl_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
