//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class ManagementEmployeeControlCreate:public drogon::DrTemplate<ManagementEmployeeControlCreate>
{
public:
	ManagementEmployeeControlCreate(){};
	virtual ~ManagementEmployeeControlCreate(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
