//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class ManagementEmployeeControl:public drogon::DrTemplate<ManagementEmployeeControl>
{
public:
	ManagementEmployeeControl(){};
	virtual ~ManagementEmployeeControl(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
