//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class ManagementEmployeeControlList:public drogon::DrTemplate<ManagementEmployeeControlList>
{
public:
	ManagementEmployeeControlList(){};
	virtual ~ManagementEmployeeControlList(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
