//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "ManagementEmployeeControlCreate.h"
#include <drogon/utils/OStringStream.h>
#include <drogon/utils/Utilities.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string ManagementEmployeeControlCreate::genText(const DrTemplateData& ManagementEmployeeControlCreate_view_data)
{
	drogon::OStringStream ManagementEmployeeControlCreate_tmp_stream;
	std::string layoutName{""};
	ManagementEmployeeControlCreate_tmp_stream << "<div class=\"card bg-base-100 shadow-xl\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "  <div class=\"card-body\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "    <h2 class=\"card-title\">Agregar Nuevo Empleado</h2>\n";
	ManagementEmployeeControlCreate_tmp_stream << "    <form\n";
	ManagementEmployeeControlCreate_tmp_stream << "      hx-post=\"/ak-acl/management/employee/control/create\"\n";
	ManagementEmployeeControlCreate_tmp_stream << "      hx-target=\"#employee-list\"\n";
	ManagementEmployeeControlCreate_tmp_stream << "      hx-swap=\"outerHTML\"\n";
	ManagementEmployeeControlCreate_tmp_stream << "      hx-on::after-request=\"if(event.detail.successful) document.getElementById('employee-form').innerHTML = ''\"\n";
	ManagementEmployeeControlCreate_tmp_stream << "      class=\"space-y-4\">\n";
ManagementEmployeeControlCreate_tmp_stream<<"\n";
	ManagementEmployeeControlCreate_tmp_stream << "      <div class=\"form-control\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "        <label class=\"label\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "          <span class=\"label-text\">Nombre</span>\n";
	ManagementEmployeeControlCreate_tmp_stream << "        </label>\n";
	ManagementEmployeeControlCreate_tmp_stream << "        <input type=\"text\" name=\"name\" class=\"input input-bordered\" required />\n";
	ManagementEmployeeControlCreate_tmp_stream << "      </div>\n";
ManagementEmployeeControlCreate_tmp_stream<<"\n";
	ManagementEmployeeControlCreate_tmp_stream << "      <div class=\"form-control\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "        <label class=\"label\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "          <span class=\"label-text\">Placa</span>\n";
	ManagementEmployeeControlCreate_tmp_stream << "        </label>\n";
	ManagementEmployeeControlCreate_tmp_stream << "        <input type=\"text\" name=\"plate\" class=\"input input-bordered\" required />\n";
	ManagementEmployeeControlCreate_tmp_stream << "      </div>\n";
ManagementEmployeeControlCreate_tmp_stream<<"\n";
	ManagementEmployeeControlCreate_tmp_stream << "      <div class=\"form-control\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "        <label class=\"label\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "          <span class=\"label-text\">Tipo de Documento</span>\n";
	ManagementEmployeeControlCreate_tmp_stream << "        </label>\n";
	ManagementEmployeeControlCreate_tmp_stream << "        <select name=\"document_type\" class=\"select select-bordered\" required>\n";
	ManagementEmployeeControlCreate_tmp_stream << "          <option value=\"\">Seleccionar...</option>\n";
	ManagementEmployeeControlCreate_tmp_stream << "          <option value=\"dni\">DNI</option>\n";
	ManagementEmployeeControlCreate_tmp_stream << "          <option value=\"ruc\">RUC</option>\n";
	ManagementEmployeeControlCreate_tmp_stream << "          <option value=\"ca\">Carnet de Extranjería</option>\n";
	ManagementEmployeeControlCreate_tmp_stream << "          <option value=\"pass\">Pasaporte</option>\n";
	ManagementEmployeeControlCreate_tmp_stream << "        </select>\n";
	ManagementEmployeeControlCreate_tmp_stream << "      </div>\n";
ManagementEmployeeControlCreate_tmp_stream<<"\n";
	ManagementEmployeeControlCreate_tmp_stream << "      <div class=\"form-control\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "        <label class=\"label\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "          <span class=\"label-text\">Número de Documento</span>\n";
	ManagementEmployeeControlCreate_tmp_stream << "        </label>\n";
	ManagementEmployeeControlCreate_tmp_stream << "        <input type=\"text\" name=\"document_number\" class=\"input input-bordered\" required />\n";
	ManagementEmployeeControlCreate_tmp_stream << "      </div>\n";
ManagementEmployeeControlCreate_tmp_stream<<"\n";
	ManagementEmployeeControlCreate_tmp_stream << "      <div class=\"flex gap-2\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "        <button type=\"submit\" class=\"btn btn-primary\">Guardar</button>\n";
	ManagementEmployeeControlCreate_tmp_stream << "        <button\n";
	ManagementEmployeeControlCreate_tmp_stream << "          type=\"button\"\n";
	ManagementEmployeeControlCreate_tmp_stream << "          class=\"btn btn-ghost\"\n";
	ManagementEmployeeControlCreate_tmp_stream << "          onclick=\"document.getElementById('employee-form').innerHTML = ''\">\n";
	ManagementEmployeeControlCreate_tmp_stream << "          Cancelar\n";
	ManagementEmployeeControlCreate_tmp_stream << "        </button>\n";
	ManagementEmployeeControlCreate_tmp_stream << "      </div>\n";
	ManagementEmployeeControlCreate_tmp_stream << "    </form>\n";
	ManagementEmployeeControlCreate_tmp_stream << "  </div>\n";
	ManagementEmployeeControlCreate_tmp_stream << "</div>\n";
if(layoutName.empty())
{
std::string ret{std::move(ManagementEmployeeControlCreate_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = ManagementEmployeeControlCreate_view_data;
auto str = std::move(ManagementEmployeeControlCreate_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
